import { test, expect } from '@playwright/test';

test('test2', async ({ page }) => {
  await page.goto('https://www.saucedemo.com/');
  await page.getByText('Swag Labs').click();
  await expect(page.locator('[data-test="username"]')).toBeVisible();
  await page.locator('[data-test="username"]').click();
  await expect(page.locator('[data-test="username"]')).toBeVisible();
  await page.locator('[data-test="username"]').click();
  await page.locator('[data-test="username"]').fill('standard_user');
  await expect(page.locator('[data-test="password"]')).toBeVisible();
  await page.locator('[data-test="password"]').dblclick();
  await page.locator('[data-test="password"]').fill('secret_sauce');
  await expect(page.locator('[data-test="login-button"]')).toBeVisible();
  await page.locator('[data-test="login-button"]').click();
  await page.locator('[data-test="add-to-cart-sauce-labs-backpack"]').click();
  await page.locator('[data-test="add-to-cart-sauce-labs-bike-light"]').click();
  await page.locator('[data-test="add-to-cart-sauce-labs-bolt-t-shirt"]').click();
  await page.locator('[data-test="add-to-cart-sauce-labs-fleece-jacket"]').click();
  await page.locator('[data-test="add-to-cart-sauce-labs-onesie"]').click();
  await page.locator('[data-test="add-to-cart-test.allthethings()-t-shirt-(red)"]').click();
  await page.locator('[data-test="shopping-cart-link"]').click();
  await page.getByText('$29.99').click();
  await page.getByText('$29.99').click();
  await page.getByText('$29.99').click();
  await page.getByText('$29.99').dblclick();
  await page.locator('[data-test="item-quantity"]').first().click();
  await expect(page.locator('[data-test="cart-list"]')).toContainText('1');
  await page.locator('[data-test="checkout"]').click();
  await expect(page.locator('[data-test="firstName"]')).toBeVisible();
  await page.locator('[data-test="firstName"]').dblclick();
  await page.locator('[data-test="firstName"]').press('CapsLock');
  await page.locator('[data-test="firstName"]').fill('E');
  await page.locator('[data-test="firstName"]').press('CapsLock');
  await page.locator('[data-test="firstName"]').fill('Ekhlas');
  await expect(page.locator('[data-test="lastName"]')).toBeVisible();
  await page.locator('[data-test="lastName"]').click();
  await page.locator('[data-test="lastName"]').press('CapsLock');
  await page.locator('[data-test="lastName"]').fill('K');
  await page.locator('[data-test="lastName"]').press('CapsLock');
  await page.locator('[data-test="lastName"]').fill('Khalel');
  await expect(page.locator('[data-test="postalCode"]')).toBeVisible();
  await page.locator('[data-test="postalCode"]').click();
  await page.locator('[data-test="postalCode"]').fill('33551');
  await expect(page.locator('[data-test="continue"]')).toBeVisible();
  await page.locator('[data-test="continue"]').click();
  await expect(page.locator('[data-test="payment-info-label"]')).toContainText('Payment Information:');
  await expect(page.locator('[data-test="payment-info-value"]')).toContainText('SauceCard #31337');
  await expect(page.locator('[data-test="shipping-info-label"]')).toContainText('Shipping Information:');
  await expect(page.locator('[data-test="shipping-info-value"]')).toContainText('Free Pony Express Delivery!');
  await expect(page.locator('[data-test="total-info-label"]')).toContainText('Price Total');
  await expect(page.locator('[data-test="tax-label"]')).toContainText('Tax: $10.40');
  await expect(page.locator('[data-test="total-label"]')).toContainText('Total: $140.34');
  await expect(page.locator('[data-test="cancel"]')).toBeVisible();
  await page.locator('[data-test="cancel"]').click();
  await page.locator('[data-test="product-sort-container"]').selectOption('hilo');
  await expect(page.locator('[data-test="remove-sauce-labs-bike-light"]')).toBeVisible();
  await page.locator('[data-test="remove-sauce-labs-bike-light"]').click();
  await page.locator('[data-test="shopping-cart-link"]').click();
  await page.locator('[data-test="checkout"]').click();
  await expect(page.locator('[data-test="firstName"]')).toBeVisible();
  await page.locator('[data-test="firstName"]').dblclick();
  await page.locator('[data-test="firstName"]').press('CapsLock');
  await page.locator('[data-test="firstName"]').fill('E');
  await page.locator('[data-test="firstName"]').press('CapsLock');
  await page.locator('[data-test="firstName"]').fill('Ekhlas');
  await expect(page.locator('[data-test="lastName"]')).toBeVisible();
  await page.locator('[data-test="lastName"]').click();
  await page.locator('[data-test="lastName"]').press('CapsLock');
  await page.locator('[data-test="lastName"]').fill('K');
  await page.locator('[data-test="lastName"]').press('CapsLock');
  await page.locator('[data-test="lastName"]').fill('Khalel');
  await expect(page.locator('[data-test="postalCode"]')).toBeVisible();
  await page.locator('[data-test="postalCode"]').click();
  await page.locator('[data-test="postalCode"]').fill('33551');
  await expect(page.locator('[data-test="continue"]')).toBeVisible();
  await page.locator('[data-test="continue"]').dblclick();
  await expect(page.locator('[data-test="finish"]')).toBeVisible();
  await page.locator('[data-test="finish"]').click();
  await expect(page.locator('[data-test="title"]')).toBeVisible();
  await expect(page.locator('[data-test="title"]')).toContainText('Checkout: Complete!');
  await expect(page.locator('[data-test="complete-header"]')).toContainText('Thank you for your order!');
  await expect(page.locator('[data-test="complete-text"]')).toContainText('Your order has been dispatched, and will arrive just as fast as the pony can get there!');
  await expect(page.locator('[data-test="back-to-products"]')).toContainText('Back Home');
});